title: Baking website template
author: Tezos baker
url: https://baking.website
description: > # this means to ignore newlines until "show_excerpts:"
  Baking website template
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag
